name: Build Docker Image

on:
  push:
    branches:
      - 'main'
    schedule:
      - cron: '0 0 * * *'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get Latest Version of Nginx 
        run: echo "NGINX_VERSION=$(curl -s 'http://nginx.org/en/download.html' | sed 's/</\'$'\n''</g' | sed -n '/>Mainline version$/,$ p' | egrep -m1 -o "([0-9]{1,}\.)+[0-9]{1,}" | sort -u)"  >> $GITHUB_ENV
      
      - name: Get Latest Version of NJS 
        run: echo "NJS_VERSION=$(curl -s curl 'https://hg.nginx.org/njs/atom-log' | grep  'http://hg.nginx.org/njs/rev/' | head -n1 | sed 's/[^0-9]//g')"  >> $GITHUB_ENV     
      
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: . 
          push: true
          tags: ankyitm/nginx-njs-compiled:latest,ankyitm/nginx-njs-compiled:${{ env.NGINX_VERSION }}-${{ env.NJS_VERSION }}
      
      - name: Notify Slack
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}
          payload: |
            {
              "text": "Docker image build result: ${{ env.NGINX_VERSION }}-${{ env.NJS_VERSION }} ",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "New Image Built and Push With Tag: ${{ env.NGINX_VERSION }}-${{ env.NJS_VERSION }}\n Download Image With:\n docker pull ankyitm/nginx-njs-compiled:latest \n or \n ankyitm/nginx-njs-compiled:${{ env.NGINX_VERSION }}-${{ env.NJS_VERSION }} \n Jenkins Deployment will trigger soon"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        
      - name: Trigger Jenkins 
        uses: wei/curl@v1
        with:
          args: ${{ secrets.TRIGGER_URL }}
